Betafooter
WildCodeSchool/lille-0920b-js-noctali-vlille pull request #9
Opened 2020-11-16 10:17 UTC by AlexisCatrix

Reprise de la branche "Footer" avec conflict merging corrigés..

2020-11-16 10:19 UTC, ThomasDruart approved these changes, later dismissed

2020-11-16 10:20 UTC, gaetan-cordonnier submitted a review, later dismissed
Good

2020-11-16 12:06 UTC, LoicBrassart requested changes
One line of DC, Fix it quickly and I'll approve

2020-11-16 12:06 UTC, LoicBrassart commented on src/components/TeamNoctali.jsx
> +  //background-color: rgb(221, 214, 214);
Dead code

2020-11-17 13:54 UTC, ThomasDruart approved these changes
ok, commented line deleted

2020-11-17 17:14 UTC, gaetan-cordonnier approved these changes

2020-11-18 08:25 UTC, LoicBrassart approved these changes
Most of the changes on this last commit were wild indentations
Please use the command I gave you to order this before pushing

No More Evil aside from that !

2020-11-18 08:27 UTC, merged